[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
